name: Multi-platform Builds (Alpine)
on: [pull_request]
jobs:
  Build:
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile-build-alpine
          builder: ${{ steps.buildx.outputs.name }}
          build-args: LMS_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64,linux/arm/v6
